### PR TITLE
Automatic conversion methods for reactive types

### PR DESCRIPTION
**Pull request by iRaiko**
Added a From<intermediate> to struct and viceversa and a Intermediate::new(old_types).

### CODE REVIEW

**Review by arctic-hen7 — CHANGES_REQUESTED** [review]
Looks great, thanks! The one thing I would change is to put those `From` implementations into the core, since I think they can be generic, can't they? I like to try to keep the macros doing as little as possible, and putting them in the core will mean that people get those implementations for free even if they have to manually implement `MakeRx` etc.

**Comment by arctic-hen7** [comment]
Also, if you could run `cargo fmt` to make CI happy, that would be great!

**Comment by iRaiko** [comment]
I might not be good enough with generics, but I have not been able to get it to work with them.
I tried some ways with From<T> for U, but it requests U to be a generic in a struct (MyStruct<U>) or with dyn MakeRx that it is not sized.

**Comment by arctic-hen7** [comment]
(Sorry for the delay, I've been sick the last week.) Ah I see what you mean. I'll merge this for now and maybe have a play around with it later and see if I can make the compiler happy about this...I'll let you know if I get anywhere!

*Not expecting CI to pass right now, I broke a few things on `main`.*

**Pull request merged**
