### PR TITLE
Openssl/vendored feature for perseus-cli

### PR DESCRIPTION
**Pull request by iRaiko**

### CODE REVIEW

**Comment by arctic-hen7** [comment]
To be clear, does this solve the problem because there's some dependency that uses `openssl`, and adding a direct dependency on it with this feature causes everything to work out?

**Comment by iRaiko** [comment]
By default reqwest will use system-native transport layer, and the default for linux is openssl (as per [reqwest](https://docs.rs/reqwest/latest/reqwest/#tls)). Features are [additive](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) so having this as an optional dependency will enable that feature for the crates that do use it. In my case, inside a docker container, the cargo install perseus-cli was not working because of openssl (I got the libssl-dev files, and set the enviroment variables), and with making it vendored it was working

**Comment by arctic-hen7** [comment]
Perfect, that's what I thought, just wanted toale sure I understand. Because it's a bit obscure for developers new to Rust, do you want to add a little comment explaining that?

**Comment by martadinata666** [comment]
The openssl vendored feature, make it build openssl from source like the [scripts/build_openssh_musl.sh](https://raw.githubusercontent.com/framesurge/perseus/main/scripts/build_openssl_musl.sh) but correct way. Instead relying on `libssl-dev` package, when on `xxxx-unknown-linux-gnu` detected correctly, it more complicated on `musl` target.

**Comment by arctic-hen7** [comment]
@iRaiko did you want to add that explanatory comment?

**Pull request merged**
