### PR TITLE
Update axum version for perseus-axum

### PR DESCRIPTION
**Pull request by wingertge**
Updates the perseus-axum server integration to version 0.6 released 5 days ago and fixes breaking changes.

### CODE REVIEW

**Review by arctic-hen7 — APPROVED** [review]
Thank you very much! I can take this off my todo list then!

Checks are failing for some reason, I'll take a look later today. This is probably fine, CI has been intermittently on strike for the last week, but I'd like to make sure. Holding off merging this until then.

**Comment by wingertge** [comment]
It's definitely the CI acting up, the failures are all about unused imports in `dflt_server.rs` which wasn't even touched by this PR

**Comment by wingertge** [comment]
After further investigating, `page_data` assumed leading slashes are always included in paths, but wildcard routes no longer include it as of 0.6. Hopefully this is the last fix that's needed.

**Comment by wingertge** [comment]
All fixed now, including the unused imports that somehow weren't caught before. Should probably squash this to remove the fix commits.

**Review by arctic-hen7 — APPROVED** [review]
Ah, thanks. LGTM!

**Pull request merged**
